### ISSUE TITLE
clear_caches is caching the wrong tables

### ISSUE THREAD

**Issue by johndwells** [nystudio107/craft-scripts#20]
Correct me if I'm wrong, but shouldn't the table names in the `clear_caches.sh` script be:

    "templatecachecriteria"
    "templatecacheelements"
    "templatecaches"

And not:

    "cache"
    "templatecaches"

?

**Comment by khalwat** [comment]
So the `cache` table is used if you have set Craft's [cacheMethod](https://craftcms.com/docs/config-settings#cacheMethod) to `db`

The `./clear_caches.sh` script only clears out your `cache` tables/directories/redis caches and the `templatecaches` table.

It's arguable whether it should clear out `templatecacheelements` and `templatecachecriteria`, I'd have to investigate a bit more to see if it makes a difference.

**Comment by khalwat** [comment]
Ahhhhh... Brandon Kelly just jogged my memory... if you drop the `templatecaches` table, it will cascade and delete the `templatecachecriteria` and `templatecacheelements` rows as well.

I remember originally when I wrote this, I had it clearing all of those tables, but I was getting errors on the `templatecachecriteria` and `templatecacheelements` tables, because they were already deleted.
