### ISSUE TITLE
Sanitise personal and private data for dev environments  

### ISSUE THREAD

**Issue by sanscheese** [nystudio107/craft-scripts#33]
Would be nice on the database syncing from LIVE to DEV to be able to sanitize the data to replace user data and sensitive information with dummy data.

If I have any luck getting it to happen, will be in touch. Unless someone else can do it faster.

**Comment by khalwat** [comment]
This is probably not something I'd do in Craft-Scripts, but you're definitely welcome to fork it and make the changes needed.

The reason is it'd be very hard to know in a general way what is sensitive, and what isn't... and then also I think it's important that the local dev database is an exact copy (cache tables aside) from the production db. But you may disagree!
